[metadata]
# replace with your username:
name = ModelPrivacy
version = 0.0.1.dev1
author = Ganghua Wang
author_email = wang9019@umn.edu
description = This package implements common model stealing attack and defending mechanisms.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/KeyWgh/ModelPrivacy
project_urls =
    Bug Tracker = https://github.com/KeyWgh/ModelPrivacy/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.6